### ISSUE TITLE
Function evaluation in select...where causes assertion error.

### ISSUE THREAD

**Issue by amullarney** [xtuml/pyxtuml#45]
The following select statement causes pyxtuml to exit:
select any emp from instances of Employee 
 where ( selected.busy() );

[ERROR]     assert xtuml.relate(*args, **kwargs)
[ERROR] AssertionError
[ERROR] pyxtuml exited with code 1

**Comment by john-tornblom** [comment]
You did not get a stack trace? It is difficult for me to pinpoint the root cause without one. @leviathan747 are those being suppressed when pyrsl/pyxtuml is invoked from bridgepoint?

**Comment by amullarney** [comment]
[INFO] Performing pyxtuml pre-build...
[ERROR] Traceback (most recent call last):
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/runpy.py", line 196, in _run_module_as_main
[ERROR]     "__main__", mod_spec)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/runpy.py", line 85, in _run_code
[ERROR]     exec(code, run_globals)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 1992, in <module>
[ERROR]     main()
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 1986, in main
[ERROR]     prebuild_model(m)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 1951, in prebuild_model
[ERROR]     prebuild_action(inst)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 1929, in prebuild_action
[ERROR]     return walker.accept(root)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/xtuml/tools.py", line 227, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 1556, in accept_BodyNode
[ERROR]     return ActionPrebuilder.accept_BodyNode(self, node)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 458, in accept_BodyNode
[ERROR]     self.accept(node.block.statement_list)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/xtuml/tools.py", line 227, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 477, in accept_StatementListNode
[ERROR]     act_smt = self.accept(child)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/xtuml/tools.py", line 227, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 649, in accept_SelectFromWhereNode
[ERROR]     v_val = self.accept(node.where_clause)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/xtuml/tools.py", line 227, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 1321, in accept_InstanceInvocationNode
[ERROR]     relate(v_val, s_dt, 820)
[ERROR]   File "/home/amullarney/.pyenv/versions/pypy3.7-7.3.5/site-packages/bridgepoint/prebuild.py", line 43, in relate
[ERROR]     assert xtuml.relate(*args, **kwargs)
[ERROR] AssertionError
[ERROR] pyxtuml exited with code 1
[INFO] ------------------------------------------------------------------------

**Comment by john-tornblom** [comment]
Seems the return value of the busy() function is not set properly. The model parser without errors?

**Comment by amullarney** [comment]
Yes - parses fine... which is why it took me some time to figure out what change had triggered the problem.Just 
  return true;

    On Monday, February 21, 2022, 10:23:05 AM PST, John Törnblom ***@***.***> wrote:  
 
 


Seems the return value of the busy() function is not set properly. The model parser without errors?
: return tru;

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cortlandstarrett** [comment]
@amullarney , there is a workspace setting that permits function calls from a where clause.  Make sure that is selected.  (Although, I think you would get an OAL parse error if it were not selected.)
